import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting operational transactions seed...');
  console.log(
    '📦 Seeding: 10 Bookings, 10 Service Orders, 10 Reminders, 5 Service Histories, 5 Reminder Logs',
  );

  const company_id = 'NGB';
  const branch_id = 'MAIN';

  // Check if company exists
  const company = await prisma.sys_Company.findUnique({
    where: { id: company_id },
  });

  if (!company) {
    console.log('❌ Company not found. Please create company first.');
    return;
  }

  console.log(`✅ Found company: ${company.name}`);

  // ============================================================
  // 1. SEED VEHICLE TYPE, BRAND, MODEL
  // ============================================================

  console.log('\n📦 Creating vehicle master data...');

  const vehicleType = await prisma.wks_VehicleType.upsert({
    where: { id: 'VT001' },
    update: {},
    create: {
      id: 'VT001',
      name: 'Mobil',
      iStatus: 'Active',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  });

  const vehicleBrands = await Promise.all([
    prisma.wks_VehicleBrand.upsert({
      where: { vehicleType_id_id: { vehicleType_id: 'VT001', id: 'VB001' } },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        id: 'VB001',
        name: 'Toyota',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.wks_VehicleBrand.upsert({
      where: { vehicleType_id_id: { vehicleType_id: 'VT001', id: 'VB002' } },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        id: 'VB002',
        name: 'Honda',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
  ]);

  const vehicleModels = await Promise.all([
    prisma.wks_VehicleModel.upsert({
      where: {
        vehicleType_id_brand_id_id: {
          vehicleType_id: 'VT001',
          brand_id: 'VB001',
          id: 'VM001',
        },
      },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        id: 'VM001',
        name: 'Avanza',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.wks_VehicleModel.upsert({
      where: {
        vehicleType_id_brand_id_id: {
          vehicleType_id: 'VT001',
          brand_id: 'VB001',
          id: 'VM002',
        },
      },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        id: 'VM002',
        name: 'Innova',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.wks_VehicleModel.upsert({
      where: {
        vehicleType_id_brand_id_id: {
          vehicleType_id: 'VT001',
          brand_id: 'VB002',
          id: 'VM003',
        },
      },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        brand_id: 'VB002',
        id: 'VM003',
        name: 'Jazz',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.wks_VehicleModel.upsert({
      where: {
        vehicleType_id_brand_id_id: {
          vehicleType_id: 'VT001',
          brand_id: 'VB002',
          id: 'VM004',
        },
      },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        brand_id: 'VB002',
        id: 'VM004',
        name: 'CRV',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.wks_VehicleModel.upsert({
      where: {
        vehicleType_id_brand_id_id: {
          vehicleType_id: 'VT001',
          brand_id: 'VB001',
          id: 'VM005',
        },
      },
      update: {},
      create: {
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        id: 'VM005',
        name: 'Fortuner',
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
  ]);

  console.log('✅ Vehicle master data created');

  // ============================================================
  // 2. SEED 5 CUSTOMERS
  // ============================================================

  console.log('\n📦 Creating customers...');

  const customers = await Promise.all([
    prisma.cmf_Customer.upsert({
      where: { company_id_id: { company_id, id: 'CUST01' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'CUST01',
        name: 'Budi Santoso',
        mobile1: '081234567890',
        email: 'budi.santoso@test.com',
        province: 'DKI Jakarta',
        city: 'Jakarta Selatan',
        address1: 'Jl. Sudirman No. 123',
        customerType: 'INDIVIDUAL',
        customerSince: new Date(),
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_Customer.upsert({
      where: { company_id_id: { company_id, id: 'CUST02' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'CUST02',
        name: 'Siti Nurhaliza',
        mobile1: '081234567891',
        email: 'siti.nurhaliza@test.com',
        province: 'Jawa Barat',
        city: 'Bandung',
        address1: 'Jl. Gatot Subroto No. 456',
        customerType: 'INDIVIDUAL',
        customerSince: new Date(),
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_Customer.upsert({
      where: { company_id_id: { company_id, id: 'CUST03' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'CUST03',
        name: 'Ahmad Dahlan',
        mobile1: '081234567892',
        email: 'ahmad.dahlan@test.com',
        province: 'DKI Jakarta',
        city: 'Jakarta Pusat',
        address1: 'Jl. Thamrin No. 789',
        customerType: 'INDIVIDUAL',
        customerSince: new Date(),
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_Customer.upsert({
      where: { company_id_id: { company_id, id: 'CUST04' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'CUST04',
        name: 'Rahma Widya',
        mobile1: '081234567893',
        email: 'rahma.widya@test.com',
        province: 'Jawa Timur',
        city: 'Surabaya',
        address1: 'Jl. Pemuda No. 321',
        customerType: 'INDIVIDUAL',
        customerSince: new Date(),
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_Customer.upsert({
      where: { company_id_id: { company_id, id: 'CUST05' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'CUST05',
        name: 'PT Maju Bersama',
        mobile1: '081234567894',
        email: 'info@majubersama.com',
        province: 'DKI Jakarta',
        city: 'Jakarta Barat',
        address1: 'Jl. Kebon Jeruk No. 654',
        customerType: 'CORPORATE',
        customerSince: new Date(),
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
  ]);

  console.log(`✅ Created ${customers.length} customers`);

  // ============================================================
  // 3. SEED 5 CUSTOMER VEHICLES
  // ============================================================

  console.log('\n📦 Creating customer vehicles...');

  const vehicles = await Promise.all([
    prisma.cmf_CustomerVehicle.upsert({
      where: {
        company_id_customer_id_id: {
          company_id,
          customer_id: 'CUST01',
          id: 'VH001',
        },
      },
      update: {},
      create: {
        company_id,
        branch_id,
        customer_id: 'CUST01',
        id: 'VH001',
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        model_id: 'VM001',
        licensePlate: 'B 9999 AAA',
        vehicleYear: 2020,
        color: 'Silver',
        currentOdometer: 45000,
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_CustomerVehicle.upsert({
      where: {
        company_id_customer_id_id: {
          company_id,
          customer_id: 'CUST02',
          id: 'VH002',
        },
      },
      update: {},
      create: {
        company_id,
        branch_id,
        customer_id: 'CUST02',
        id: 'VH002',
        vehicleType_id: 'VT001',
        brand_id: 'VB002',
        model_id: 'VM003',
        licensePlate: 'D 9999 DEF',
        vehicleYear: 2021,
        color: 'White',
        currentOdometer: 30000,
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_CustomerVehicle.upsert({
      where: {
        company_id_customer_id_id: {
          company_id,
          customer_id: 'CUST03',
          id: 'VH003',
        },
      },
      update: {},
      create: {
        company_id,
        branch_id,
        customer_id: 'CUST03',
        id: 'VH003',
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        model_id: 'VM002',
        licensePlate: 'B 9999 GHI',
        vehicleYear: 2019,
        color: 'Black',
        currentOdometer: 60000,
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_CustomerVehicle.upsert({
      where: {
        company_id_customer_id_id: {
          company_id,
          customer_id: 'CUST04',
          id: 'VH004',
        },
      },
      update: {},
      create: {
        company_id,
        branch_id,
        customer_id: 'CUST04',
        id: 'VH004',
        vehicleType_id: 'VT001',
        brand_id: 'VB002',
        model_id: 'VM004',
        licensePlate: 'L 9999 JKL',
        vehicleYear: 2022,
        color: 'Red',
        currentOdometer: 25000,
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
    prisma.cmf_CustomerVehicle.upsert({
      where: {
        company_id_customer_id_id: {
          company_id,
          customer_id: 'CUST05',
          id: 'VH005',
        },
      },
      update: {},
      create: {
        company_id,
        branch_id,
        customer_id: 'CUST05',
        id: 'VH005',
        vehicleType_id: 'VT001',
        brand_id: 'VB001',
        model_id: 'VM005',
        licensePlate: 'B 9999 MNO',
        vehicleYear: 2021,
        color: 'White',
        currentOdometer: 35000,
        iStatus: 'Active',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    }),
  ]);

  console.log(`✅ Created ${vehicles.length} customer vehicles`);

  // ============================================================
  // 4. SEED 10 SERVICE BOOKINGS
  // ============================================================

  console.log('\n📦 Creating service bookings...');

  const bookingDates = [
    new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  ];

  const bookings = await Promise.all([
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-001' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-001',
        bookingNumber: 'BKG-2025-00001',
        bookingDate: bookingDates[0],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        preferredDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        preferredStartTime: '09:00',
        preferredEndTime: '11:00',
        complaintNotes: 'Mesin kasar, perlu service berkala',
        status: 'PENDING',
        source: 'WEB',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[0],
        updatedAt: bookingDates[0],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-002' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-002',
        bookingNumber: 'BKG-2025-00002',
        bookingDate: bookingDates[1],
        customer_id: 'CUST02',
        customerVehicle_id: 'VH002',
        vehicle_customer_id: 'CUST02',
        preferredDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        preferredStartTime: '10:00',
        preferredEndTime: '12:00',
        complaintNotes: 'Rem bunyi, perlu cek',
        status: 'CONFIRMED',
        source: 'APP',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[1],
        updatedAt: bookingDates[1],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-003' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-003',
        bookingNumber: 'BKG-2025-00003',
        bookingDate: bookingDates[2],
        customer_id: 'CUST03',
        customerVehicle_id: 'VH003',
        vehicle_customer_id: 'CUST03',
        preferredDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        preferredStartTime: '13:00',
        preferredEndTime: '15:00',
        complaintNotes: 'AC kurang dingin',
        status: 'CHECKED_IN',
        source: 'PHONE',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[2],
        updatedAt: bookingDates[2],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-004' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-004',
        bookingNumber: 'BKG-2025-00004',
        bookingDate: bookingDates[3],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        preferredDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        preferredStartTime: '14:00',
        preferredEndTime: '16:00',
        complaintNotes: 'Ganti oli rutin',
        status: 'CONFIRMED',
        source: 'WEB',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[3],
        updatedAt: bookingDates[3],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-005' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-005',
        bookingNumber: 'BKG-2025-00005',
        bookingDate: bookingDates[4],
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        preferredDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        preferredStartTime: '08:00',
        preferredEndTime: '10:00',
        complaintNotes: 'Ban bocor, perlu perbaikan',
        status: 'PENDING',
        source: 'WALKIN',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[4],
        updatedAt: bookingDates[4],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-006' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-006',
        bookingNumber: 'BKG-2025-00006',
        bookingDate: bookingDates[5],
        customer_id: 'CUST05',
        customerVehicle_id: 'VH005',
        vehicle_customer_id: 'CUST05',
        preferredDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
        preferredStartTime: '09:00',
        preferredEndTime: '11:00',
        complaintNotes: 'Service 40rb km',
        status: 'CONFIRMED',
        source: 'APP',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[5],
        updatedAt: bookingDates[5],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-007' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-007',
        bookingNumber: 'BKG-2025-00007',
        bookingDate: bookingDates[6],
        customer_id: 'CUST02',
        customerVehicle_id: 'VH002',
        vehicle_customer_id: 'CUST02',
        preferredDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        preferredStartTime: '10:00',
        preferredEndTime: '12:00',
        complaintNotes: 'Ganti kampas rem',
        status: 'CHECKED_IN',
        source: 'WEB',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[6],
        updatedAt: bookingDates[6],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-008' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-008',
        bookingNumber: 'BKG-2025-00008',
        bookingDate: bookingDates[7],
        customer_id: 'CUST03',
        customerVehicle_id: 'VH003',
        vehicle_customer_id: 'CUST03',
        preferredDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
        preferredStartTime: '13:00',
        preferredEndTime: '15:00',
        complaintNotes: 'Tune up mesin',
        status: 'CONFIRMED',
        source: 'PHONE',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[7],
        updatedAt: bookingDates[7],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-009' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-009',
        bookingNumber: 'BKG-2025-00009',
        bookingDate: bookingDates[8],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        preferredDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
        preferredStartTime: '14:00',
        preferredEndTime: '16:00',
        complaintNotes: 'Ganti baterai',
        status: 'PENDING',
        source: 'WALKIN',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[8],
        updatedAt: bookingDates[8],
      },
    }),
    prisma.wks_ServiceBooking.upsert({
      where: { company_id_id: { company_id, id: 'BKG-010' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'BKG-010',
        bookingNumber: 'BKG-2025-00010',
        bookingDate: bookingDates[9],
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        preferredDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        preferredStartTime: '08:00',
        preferredEndTime: '10:00',
        complaintNotes: 'Inspection service',
        status: 'CONFIRMED',
        source: 'APP',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[9],
        updatedAt: bookingDates[9],
      },
    }),
  ]);

  console.log(`✅ Created ${bookings.length} service bookings`);

  // ============================================================
  // 5. SEED 10 SERVICE ORDERS
  // ============================================================

  console.log('\n📦 Creating service orders...');

  const serviceOrders = await Promise.all([
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-001' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-001',
        orderNumber: 'SO-2025-00001',
        orderDate: bookingDates[0],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        odometerIn: 45000,
        fuelLevel: 'HALF',
        vehicleConditionNotes: 'Kendaraan bersih, tidak ada goresan',
        customerComplaint: 'Mesin kasar',
        serviceRequest: 'Ganti oli dan filter',
        serviceCost: 350000,
        partsCost: 500000,
        totalAmount: 850000,
        orderStatus: 'COMPLETED',
        paymentStatus: 'PAID',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[0],
        updatedAt: bookingDates[0],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-002' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-002',
        orderNumber: 'SO-2025-00002',
        orderDate: bookingDates[1],
        customer_id: 'CUST02',
        customerVehicle_id: 'VH002',
        vehicle_customer_id: 'CUST02',
        odometerIn: 30000,
        fuelLevel: 'QUARTER',
        vehicleConditionNotes: 'Ada goresan kecil di bumper',
        customerComplaint: 'Rem bunyi',
        serviceRequest: 'Cek kampas rem',
        serviceCost: 200000,
        partsCost: 300000,
        totalAmount: 500000,
        orderStatus: 'QC_CHECK',
        paymentStatus: 'PARTIAL',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[1],
        updatedAt: bookingDates[1],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-003' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-003',
        orderNumber: 'SO-2025-00003',
        orderDate: bookingDates[2],
        customer_id: 'CUST03',
        customerVehicle_id: 'VH003',
        vehicle_customer_id: 'CUST03',
        odometerIn: 60000,
        fuelLevel: 'FULL',
        vehicleConditionNotes: 'Kondisi baik',
        customerComplaint: 'AC kurang dingin',
        serviceRequest: 'Service AC',
        serviceCost: 400000,
        partsCost: 450000,
        totalAmount: 850000,
        orderStatus: 'COMPLETED',
        paymentStatus: 'PAID',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[2],
        updatedAt: bookingDates[2],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-004' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-004',
        orderNumber: 'SO-2025-00004',
        orderDate: bookingDates[3],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        odometerIn: 46000,
        fuelLevel: 'HALF',
        vehicleConditionNotes: 'Tidak ada masalah',
        customerComplaint: 'Ganti oli rutin',
        serviceRequest: 'Service berkala',
        serviceCost: 250000,
        partsCost: 350000,
        totalAmount: 600000,
        orderStatus: 'CONFIRMED',
        paymentStatus: 'UNPAID',
        priority: 'LOW',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[3],
        updatedAt: bookingDates[3],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-005' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-005',
        orderNumber: 'SO-2025-00005',
        orderDate: bookingDates[4],
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        odometerIn: 25000,
        fuelLevel: 'EMPTY',
        vehicleConditionNotes: 'Ban bocor sudah diperbaiki',
        customerComplaint: 'Ban bocor',
        serviceRequest: 'Perbaikan ban',
        serviceCost: 150000,
        partsCost: 200000,
        totalAmount: 350000,
        orderStatus: 'COMPLETED',
        paymentStatus: 'PAID',
        priority: 'HIGH',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[4],
        updatedAt: bookingDates[4],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-006' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-006',
        orderNumber: 'SO-2025-00006',
        orderDate: bookingDates[5],
        customer_id: 'CUST05',
        customerVehicle_id: 'VH005',
        vehicle_customer_id: 'CUST05',
        odometerIn: 35000,
        fuelLevel: 'QUARTER',
        vehicleConditionNotes: 'Kondisi prima',
        customerComplaint: 'Service 40rb km',
        serviceRequest: 'Service berkala lengkap',
        serviceCost: 750000,
        partsCost: 800000,
        totalAmount: 1550000,
        orderStatus: 'IN_PROGRESS',
        paymentStatus: 'UNPAID',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[5],
        updatedAt: bookingDates[5],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-007' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-007',
        orderNumber: 'SO-2025-00007',
        orderDate: bookingDates[6],
        customer_id: 'CUST02',
        customerVehicle_id: 'VH002',
        vehicle_customer_id: 'CUST02',
        odometerIn: 32000,
        fuelLevel: 'HALF',
        vehicleConditionNotes: 'Tidak ada catatan',
        customerComplaint: 'Ganti kampas rem',
        serviceRequest: 'Service rem depan belakang',
        serviceCost: 300000,
        partsCost: 400000,
        totalAmount: 700000,
        orderStatus: 'ON_HOLD',
        paymentStatus: 'UNPAID',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[6],
        updatedAt: bookingDates[6],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-008' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-008',
        orderNumber: 'SO-2025-00008',
        orderDate: bookingDates[7],
        customer_id: 'CUST03',
        customerVehicle_id: 'VH003',
        vehicle_customer_id: 'CUST03',
        odometerIn: 61000,
        fuelLevel: 'FULL',
        vehicleConditionNotes: 'Kondisi baik',
        customerComplaint: 'Tune up mesin',
        serviceRequest: 'Tune up lengkap',
        serviceCost: 500000,
        partsCost: 600000,
        totalAmount: 1100000,
        orderStatus: 'IN_PROGRESS',
        paymentStatus: 'UNPAID',
        priority: 'HIGH',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[7],
        updatedAt: bookingDates[7],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-009' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-009',
        orderNumber: 'SO-2025-00009',
        orderDate: bookingDates[8],
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        odometerIn: 47000,
        fuelLevel: 'QUARTER',
        vehicleConditionNotes: 'Ban aus',
        customerComplaint: 'Ganti baterai',
        serviceRequest: 'Ganti baterai AGM',
        serviceCost: 300000,
        partsCost: 250000,
        totalAmount: 550000,
        orderStatus: 'COMPLETED',
        paymentStatus: 'PAID',
        priority: 'NORMAL',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[8],
        updatedAt: bookingDates[8],
      },
    }),
    prisma.wks_ServiceOrder.upsert({
      where: { company_id_id: { company_id, id: 'SO-010' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SO-010',
        orderNumber: 'SO-2025-00010',
        orderDate: bookingDates[9],
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        odometerIn: 26000,
        fuelLevel: 'HALF',
        vehicleConditionNotes: 'Kondisi baik',
        customerComplaint: 'Inspection service',
        serviceRequest: 'Pemeriksaan lengkap',
        serviceCost: 200000,
        partsCost: 100000,
        totalAmount: 300000,
        orderStatus: 'DRAFT',
        paymentStatus: 'UNPAID',
        priority: 'LOW',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[9],
        updatedAt: bookingDates[9],
      },
    }),
  ]);

  console.log(`✅ Created ${serviceOrders.length} service orders`);

  // ============================================================
  // 6. SEED 10 REMINDERS
  // ============================================================

  console.log('\n📦 Creating reminders...');

  const reminders = await Promise.all([
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-001' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-001',
        reminderNumber: 'REM-2025-00001',
        entityType: 'SERVICE_ORDER',
        entity_id: 'SO-001',
        reminderType: 'SCHEDULED_SERVICE',
        title: 'Reminder Service Order SO-001',
        message: 'Jangan lupa follow up service order SO-001',
        scheduledDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        scheduledTime: '09:00',
        sendBeforeDays: 1,
        sendBeforeHours: 24,
        customer_id: 'CUST01',
        recipientPhone: '081234567890',
        recipientEmail: 'budi.santoso@test.com',
        channels: 'WA,EM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-002' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-002',
        reminderNumber: 'REM-2025-00002',
        entityType: 'BOOKING',
        entity_id: 'BKG-002',
        reminderType: 'APPOINTMENT',
        title: 'Reminder Appointment Booking BKG-002',
        message: 'Customer appointment akan datang besok',
        scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        scheduledTime: '10:00',
        sendBeforeDays: 1,
        sendBeforeHours: 2,
        customer_id: 'CUST02',
        recipientPhone: '081234567891',
        recipientEmail: 'siti.nurhaliza@test.com',
        channels: 'WA,EM,SM',
        status: 'SCHEDULED',
        sentCount: 1,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-003' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-003',
        reminderNumber: 'REM-2025-00003',
        entityType: 'SERVICE_ORDER',
        entity_id: 'SO-003',
        reminderType: 'SERVICE_DUE',
        title: 'Reminder Service Order Due SO-003',
        message: 'Service order sudah due dan perlu segera diselesaikan',
        scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        customer_id: 'CUST03',
        recipientPhone: '081234567892',
        recipientEmail: 'ahmad.dahlan@test.com',
        channels: 'WA',
        status: 'SENT',
        sentCount: 1,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-004' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-004',
        reminderNumber: 'REM-2025-00004',
        entityType: 'BOOKING',
        entity_id: 'BKG-004',
        reminderType: 'APPOINTMENT',
        title: 'Reminder Booking Follow Up BKG-004',
        message: 'Konfirmasi ulang booking dengan customer',
        scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        scheduledTime: '14:00',
        sendBeforeDays: 2,
        sendBeforeHours: 24,
        customer_id: 'CUST01',
        recipientPhone: '081234567890',
        recipientEmail: 'budi.santoso@test.com',
        channels: 'WA,EM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-005' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-005',
        reminderNumber: 'REM-2025-00005',
        entityType: 'SERVICE_ORDER',
        entity_id: 'SO-005',
        reminderType: 'SCHEDULED_SERVICE',
        title: 'Reminder Next Service SO-005',
        message: 'Informasi next service untuk kendaraan customer',
        scheduledDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        scheduledTime: '08:00',
        sendBeforeDays: 7,
        customer_id: 'CUST04',
        recipientPhone: '081234567893',
        recipientEmail: 'rahma.widya@test.com',
        channels: 'EM,SM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-006' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-006',
        reminderNumber: 'REM-2025-00006',
        entityType: 'PAYMENT',
        entity_id: 'SO-006',
        reminderType: 'PAYMENT_DUE',
        title: 'Reminder Payment Due SO-006',
        message: 'Pembayaran service order sudah jatuh tempo',
        scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        sendBeforeDays: 3,
        customer_id: 'CUST05',
        recipientPhone: '081234567894',
        recipientEmail: 'info@majubersama.com',
        channels: 'WA,EM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-007' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-007',
        reminderNumber: 'REM-2025-00007',
        entityType: 'BOOKING',
        entity_id: 'BKG-007',
        reminderType: 'APPOINTMENT',
        title: 'Reminder Booking Appointment BKG-007',
        message: 'Customer akan datang untuk service rem',
        scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        scheduledTime: '10:00',
        sendBeforeDays: 1,
        sendBeforeHours: 24,
        customer_id: 'CUST02',
        recipientPhone: '081234567891',
        recipientEmail: 'siti.nurhaliza@test.com',
        channels: 'WA',
        status: 'SCHEDULED',
        sentCount: 1,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-008' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-008',
        reminderNumber: 'REM-2025-00008',
        entityType: 'SERVICE_ORDER',
        entity_id: 'SO-008',
        reminderType: 'FOLLOW_UP',
        title: 'Reminder Follow Up SO-008',
        message: 'Follow up progress service order',
        scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        scheduledTime: '15:00',
        sendBeforeDays: 1,
        customer_id: 'CUST03',
        recipientPhone: '081234567892',
        recipientEmail: 'ahmad.dahlan@test.com',
        channels: 'WA,EM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-009' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-009',
        reminderNumber: 'REM-2025-00009',
        entityType: 'VEHICLE_MAINTENANCE',
        entity_id: 'VH001',
        reminderType: 'SCHEDULED_SERVICE',
        title: 'Reminder Service Berkala Kendaraan',
        message: 'Kendaraan perlu service rutin 50rb km',
        scheduledDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        sendBeforeDays: 7,
        customer_id: 'CUST01',
        recipientPhone: '081234567890',
        recipientEmail: 'budi.santoso@test.com',
        channels: 'WA,EM,SM',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_Reminder.upsert({
      where: { company_id_id: { company_id, id: 'REM-010' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'REM-010',
        reminderNumber: 'REM-2025-00010',
        entityType: 'CUSTOM',
        entity_id: 'BKG-010',
        reminderType: 'CUSTOM',
        title: 'Custom Reminder untuk Booking',
        message: 'Custom reminder untuk customer VIP',
        scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        scheduledTime: '09:00',
        sendBeforeDays: 1,
        sendBeforeHours: 24,
        customer_id: 'CUST04',
        recipientPhone: '081234567893',
        recipientEmail: 'rahma.widya@test.com',
        channels: 'WA',
        status: 'PENDING',
        sentCount: 0,
        maxRetries: 3,
        retryCount: 0,
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    }),
  ]);

  console.log(`✅ Created ${reminders.length} reminders`);

  // ============================================================
  // 6. SEED SERVICE HISTORY
  // ============================================================

  console.log('\n📦 Creating service history...');

  const serviceHistories = await Promise.all([
    prisma.wks_ServiceHistory.upsert({
      where: { company_id_id: { company_id, id: 'SH-001' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SH-001',
        serviceOrder_id: 'SO-001',
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        serviceDate: bookingDates[0],
        orderNumber: 'SO-2025-00001',
        serviceSummary: 'Ganti oli mesin dan filter oli',
        partsReplaced: 'Shell Helix HX7 5W-30 4L, Filter Oli Toyota',
        odometerReading: 45000,
        totalServiceCost: 350000,
        totalPartsCost: 500000,
        totalAmount: 850000,
        nextServiceDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        nextServiceOdometer: 50000,
        mechanicName: 'Mekanik Budi',
        customerRating: 5,
        customerFeedback:
          'Service sangat memuaskan, mekanik sangat profesional',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[0],
        updatedAt: bookingDates[0],
      },
    }),
    prisma.wks_ServiceHistory.upsert({
      where: { company_id_id: { company_id, id: 'SH-002' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SH-002',
        serviceOrder_id: 'SO-003',
        customer_id: 'CUST03',
        customerVehicle_id: 'VH003',
        vehicle_customer_id: 'CUST03',
        serviceDate: bookingDates[2],
        orderNumber: 'SO-2025-00003',
        serviceSummary: 'Service AC dan tune up mesin',
        partsReplaced: 'Freon R134a, Filter AC, Busi',
        odometerReading: 60000,
        totalServiceCost: 400000,
        totalPartsCost: 450000,
        totalAmount: 850000,
        nextServiceDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        nextServiceOdometer: 70000,
        mechanicName: 'Mekanik Andi',
        customerRating: 4,
        customerFeedback: 'AC sudah dingin lagi, terima kasih',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[2],
        updatedAt: bookingDates[2],
      },
    }),
    prisma.wks_ServiceHistory.upsert({
      where: { company_id_id: { company_id, id: 'SH-003' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SH-003',
        serviceOrder_id: 'SO-005',
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        serviceDate: bookingDates[4],
        orderNumber: 'SO-2025-00005',
        serviceSummary: 'Perbaikan ban dan service cepat',
        partsReplaced: 'Ban Tubeless 16 inch',
        odometerReading: 25000,
        totalServiceCost: 150000,
        totalPartsCost: 200000,
        totalAmount: 350000,
        nextServiceDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        nextServiceOdometer: 30000,
        mechanicName: 'Mekanik Candra',
        customerRating: 5,
        customerFeedback: 'Fast response, ban langsung bisa dipakai',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[4],
        updatedAt: bookingDates[4],
      },
    }),
    prisma.wks_ServiceHistory.upsert({
      where: { company_id_id: { company_id, id: 'SH-004' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SH-004',
        serviceOrder_id: 'SO-009',
        customer_id: 'CUST01',
        customerVehicle_id: 'VH001',
        vehicle_customer_id: 'CUST01',
        serviceDate: bookingDates[8],
        orderNumber: 'SO-2025-00009',
        serviceSummary: 'Ganti baterai AGM dan service umum',
        partsReplaced: 'Baterai AGM 70Ah',
        odometerReading: 47000,
        totalServiceCost: 300000,
        totalPartsCost: 250000,
        totalAmount: 550000,
        nextServiceDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        nextServiceOdometer: 50000,
        mechanicName: 'Mekanik Budi',
        customerRating: 5,
        customerFeedback: 'Baterai baru, starter lebih kuat',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[8],
        updatedAt: bookingDates[8],
      },
    }),
    prisma.wks_ServiceHistory.upsert({
      where: { company_id_id: { company_id, id: 'SH-005' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'SH-005',
        serviceOrder_id: 'SO-010',
        customer_id: 'CUST04',
        customerVehicle_id: 'VH004',
        vehicle_customer_id: 'CUST04',
        serviceDate: bookingDates[9],
        orderNumber: 'SO-2025-00010',
        serviceSummary: 'Inspection lengkap dan perawatan',
        partsReplaced: 'Filter udara, Filter AC',
        odometerReading: 26000,
        totalServiceCost: 200000,
        totalPartsCost: 100000,
        totalAmount: 300000,
        nextServiceDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
        nextServiceOdometer: 40000,
        mechanicName: 'Mekanik Candra',
        customerRating: 4,
        customerFeedback: 'Kendaraan tetap prima',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: bookingDates[9],
        updatedAt: bookingDates[9],
      },
    }),
  ]);

  console.log(`✅ Created ${serviceHistories.length} service histories`);

  // ============================================================
  // 7. SEED REMINDER LOG
  // ============================================================

  console.log('\n📦 Creating reminder logs...');

  const reminderLogs = await Promise.all([
    prisma.sys_ReminderLog.upsert({
      where: { company_id_id: { company_id, id: 'RML-001' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'RML-001',
        reminder_id: 'REM-002',
        logType: 'SENT',
        channel: 'WHATSAPP',
        sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        message: 'Customer appointment akan datang besok pukul 10:00 WIB',
        recipient: '081234567891',
        status: 'Success',
        responseCode: '200',
        responseMessage: 'Message sent successfully',
        externalId: 'WA-MSG-123456789',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_ReminderLog.upsert({
      where: { company_id_id: { company_id, id: 'RML-002' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'RML-002',
        reminder_id: 'REM-002',
        logType: 'SENT',
        channel: 'EMAIL',
        sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        message: 'Reminder appointment untuk tomorrow',
        recipient: 'siti.nurhaliza@test.com',
        status: 'Success',
        responseCode: '200',
        responseMessage: 'Email sent successfully',
        externalId: 'EML-MSG-987654321',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_ReminderLog.upsert({
      where: { company_id_id: { company_id, id: 'RML-003' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'RML-003',
        reminder_id: 'REM-003',
        logType: 'FAILED',
        channel: 'WHATSAPP',
        sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        message: 'Service order sudah due dan perlu segera diselesaikan',
        recipient: '081234567892',
        status: 'Failed',
        responseCode: '400',
        responseMessage: 'Invalid phone number format',
        errorMessage: 'Phone number format tidak valid',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_ReminderLog.upsert({
      where: { company_id_id: { company_id, id: 'RML-004' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'RML-004',
        reminder_id: 'REM-007',
        logType: 'SENT',
        channel: 'SMS',
        sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        message: 'Customer akan datang untuk service rem besok',
        recipient: '081234567891',
        status: 'Success',
        responseCode: '200',
        responseMessage: 'SMS sent successfully',
        externalId: 'SMS-MSG-456789123',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    }),
    prisma.sys_ReminderLog.upsert({
      where: { company_id_id: { company_id, id: 'RML-005' } },
      update: {},
      create: {
        company_id,
        branch_id,
        id: 'RML-005',
        reminder_id: 'REM-010',
        logType: 'SENT',
        channel: 'WHATSAPP',
        sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        message: 'Reminder custom untuk booking appointment',
        recipient: '081234567893',
        status: 'Success',
        responseCode: '200',
        responseMessage: 'Message sent successfully',
        externalId: 'WA-MSG-789123456',
        transactionStatus: 'ENTRY',
        isDeleted: false,
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
    }),
  ]);

  console.log(`✅ Created ${reminderLogs.length} reminder logs`);

  // ============================================================
  // SUMMARY
  // ============================================================

  console.log('\n✅ ✅ ✅ OPERATIONAL TRANSACTIONS SEED COMPLETED! ✅ ✅ ✅');
  console.log('\n📊 Summary:');
  console.log(`   • ${bookings.length} service bookings created`);
  console.log(`   • ${serviceOrders.length} service orders created`);
  console.log(`   • ${reminders.length} reminders created`);
  console.log(`   • ${serviceHistories.length} service histories created`);
  console.log(`   • ${reminderLogs.length} reminder logs created`);
  console.log(
    '\n🚀 Ready for testing pagination, sorting, search, and filter!',
  );
}

main()
  .catch((e) => {
    console.error('❌ Error seeding operational transactions:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
